### ISSUE TITLE
Errors using DEM

### ISSUE THREAD

**Issue by xhuang-jpl** [dbekaert/RAiDER#403] opened 2022-11-22 01:31 UTC
try to run the program using the DEM, there is an error coming out "No such driver registered: %s, b''nc". The output is the netCDF format. please see more in the attached figure. The yaml file is also attached.  Have tested all the tiff file, which are all readable by GDAL. I could share the DEM etc file if you need to test. Thank you

![image](https://user-images.githubusercontent.com/118782850/203190740-85eb893a-e42e-4cd1-ad40-ce495adfa324.png)
[raiderDelay.yaml.zip](https://github.com/dbekaert/RAiDER/files/10061787/raiderDelay.yaml.zip)

**Comment by jlmaurer** [comment] 2022-11-22 02:46
@xhuang-jpl thanks for posting the yaml file! The issue is that you have specified the output file format as NETCDF, but [writing netcdfs is presently banned](https://rasterio.readthedocs.io/en/latest/api/rasterio.drivers.html) in rasterio. Try changing `raster_format` to `GTiff` for example to see if that runs. We should probably raise an error when a user passes an invalid format. 

I noticed  that your yaml file mentions a "cube," but if you give raster inputs to RAiDER it will return a raster output, not a cube. To get a NETCDF cube, you can specify a bounding box and a grid spacing (see [this example](https://github.com/dbekaert/RAiDER-docs/blob/master/notebooks/RAiDER_tutorial/example_yamls/nisar_example.yml)).

**Comment by xhuang-jpl** [comment] 2022-11-22 18:23
Thank you @jlmaurer , I have revised the format as the GTiff, seems that no issues about the driver, but there is one more error comes out, please see attached. Thanks again
<img width="897" alt="image" src="https://user-images.githubusercontent.com/118782850/203392093-4cec9996-3060-4c7e-93d1-02526ab60e2c.png">

**Comment by bbuzz31** [comment] 2022-11-22 19:08
This is fixed in my new branch: https://github.com/dbekaert/RAiDER/pull/402

**Comment by xhuang-jpl** [comment] 2022-11-22 23:08
tested, seems working. Thank you @bbuzz31. in addition, is the **los** the incidence angle? Thanks

**Comment by xhuang-jpl** [comment] 2022-11-22 23:52
must the dem be in WGS84 projection? I tested a dem in UTM projection along with its lat and lon file. Here is the error:
![image](https://user-images.githubusercontent.com/118782850/203444117-d649b000-6495-4964-9c66-8f095fa22913.png)

I guess the bounding box is calculated by the dem file instead of using the lat/lon files?

**Comment by bbuzz31** [comment] 2022-11-23 01:21
> tested, seems working. Thank you @bbuzz31. in addition, is the **los** the incidence angle? Thanks

No LOS is the line of sight, different from incidence angle. [This](https://esamultimedia.esa.int/multimedia/publications/TM-19/TM-19_InSAR_web.pdf) may be helpful

**Comment by bbuzz31** [comment] 2022-11-23 01:23
> must the dem be in WGS84 projection? I tested a dem in UTM projection along with its lat and lon file. Here is the error: ![image](https://user-images.githubusercontent.com/118782850/203444117-d649b000-6495-4964-9c66-8f095fa22913.png)
> 
> I guess the bounding box is calculated by the dem file instead of using the lat/lon files?

I guess not. Can you provide the DEM and config file? If they're too big you can LFT them to me at buzzanga.jpl.nasa.gov

**Comment by xhuang-jpl** [comment] 2022-11-23 01:31
> 

Thank you @bbuzz31  I mean the los_file in the los_group

![image](https://user-images.githubusercontent.com/118782850/203453276-c83fee1f-d3b6-4fef-b6b7-960e6dabeffe.png)

**Comment by xhuang-jpl** [comment] 2022-11-23 02:09
> 

Have sent the dem, lat, lon and yaml file, please let me know if you receive them. Thank you

**Comment by xhuang-jpl** [comment] 2022-11-23 19:32
Test the new branch, seems working for different projection. I delete the dem item, and error like this,
 
![image](https://user-images.githubusercontent.com/118782850/203631292-4efc6a18-8739-4810-b3dd-7f2a22da3daa.png)

since the lat, lon, and hgt files have been specified, is the DEM still necessary? thanks

**Comment by jlmaurer** [comment] 2022-11-28 14:42
Hi @xhuang-jpl, for rasters the LOS file is a two-band file with incidence angle and heading that is generated by ISCE during e.g. Tops processing. @bbuzz31 is also working on implementing a GUNW parser that will automatically extract the LOS information from the GUNW, but I'm not sure if that's fully functioning yet. The other thing you can do is just pass the orbit file corresponding to your acquisition, and RAiDER will calculate the look vectors from that.

**Comment by xhuang-jpl** [comment] 2022-11-28 17:19
Thank you @jlmaurer!

**Comment by bbuzz31** [comment] 2022-11-28 20:20
FYI: This branch will not work with HRRR

**Closed** 2022-12-05 21:04 UTC
