### ISSUE TITLE
[BUG] second example command (by running the helper command) fails due to losreader problem

### ISSUE THREAD

**Issue by leiyangleon** [dbekaert/RAiDER#273] opened 2021-03-04 18:23 UTC
**Describe the bug**
When running the 2nd raiderDelay helper command, it fails due to array dimension error in the losreader.py file.

**To Reproduce**

1. Command used
`raiderDelay.py --date 20200103 --time 23:00:00 -b 39 40 -79 -78 --model GMAO --zref 15000 --heightlvs 0 100 200 -v
`
2. Error Output
```
Weather model GMAO is available from 2014-02-20 00:00:00-Present
WARNING: Rounded given hour from  23 to 0
Traceback (most recent call last):
  File "/opt/anaconda3/envs/RAiDER/bin/raiderDelay.py", line 4, in <module>
    __import__('pkg_resources').run_script('RAiDER==0.0.1', 'raiderDelay.py')
  File "/opt/anaconda3/envs/RAiDER/lib/python3.7/site-packages/pkg_resources/__init__.py", line 665, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/opt/anaconda3/envs/RAiDER/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1463, in run_script
    exec(code, namespace, namespace)
  File "/opt/anaconda3/envs/RAiDER/lib/python3.7/site-packages/RAiDER-0.0.1-py3.7-macosx-10.9-x86_64.egg/EGG-INFO/scripts/raiderDelay.py", line 12, in <module>
    parseCMD()
  File "/opt/anaconda3/envs/RAiDER/lib/python3.7/site-packages/RAiDER-0.0.1-py3.7-macosx-10.9-x86_64.egg/RAiDER/runProgram.py", line 196, in parseCMD
    _tropo_delay(new_args)
  File "/opt/anaconda3/envs/RAiDER/lib/python3.7/site-packages/RAiDER-0.0.1-py3.7-macosx-10.9-x86_64.egg/RAiDER/runProgram.py", line 208, in _tropo_delay
    (_, _) = tropo_delay(args_copy)
  File "/opt/anaconda3/envs/RAiDER/lib/python3.7/site-packages/RAiDER-0.0.1-py3.7-macosx-10.9-x86_64.egg/RAiDER/delay.py", line 153, in tropo_delay
    los = getLookVectors(los, lats, lons, hgts, zref)
  File "/opt/anaconda3/envs/RAiDER/lib/python3.7/site-packages/RAiDER-0.0.1-py3.7-macosx-10.9-x86_64.egg/RAiDER/losreader.py", line 338, in getLookVectors
    look_vecs = _getZenithLookVecs(lat, lon, hgt, zref=zref)
  File "/opt/anaconda3/envs/RAiDER/lib/python3.7/site-packages/RAiDER-0.0.1-py3.7-macosx-10.9-x86_64.egg/RAiDER/losreader.py", line 320, in _getZenithLookVecs
    zenLookVecs = (np.array((e, n, u)).T * (zref - heights)[..., np.newaxis])
ValueError: operands could not be broadcast together with shapes (2,3) (3,1)
```

**Comment by jlmaurer** [comment] 2021-03-04 20:49
@leiyangleon yes I saw this bug last night when I was testing as well. I think I have the fix in place, will push asap.

**Comment by leiyangleon** [comment] 2021-03-08 19:58
@jlmaurer the command still fails but with a new error now:

```
Traceback (most recent call last):
  File "/opt/anaconda3/envs/RAiDER/bin/raiderDelay.py", line 4, in <module>
    __import__('pkg_resources').run_script('RAiDER==0.0.1', 'raiderDelay.py')
  File "/opt/anaconda3/envs/RAiDER/lib/python3.7/site-packages/pkg_resources/__init__.py", line 665, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/opt/anaconda3/envs/RAiDER/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1463, in run_script
    exec(code, namespace, namespace)
  File "/opt/anaconda3/envs/RAiDER/lib/python3.7/site-packages/RAiDER-0.0.1-py3.7-macosx-10.9-x86_64.egg/EGG-INFO/scripts/raiderDelay.py", line 12, in <module>
    parseCMD()
  File "/opt/anaconda3/envs/RAiDER/lib/python3.7/site-packages/RAiDER-0.0.1-py3.7-macosx-10.9-x86_64.egg/RAiDER/runProgram.py", line 154, in parseCMD
    args = checkArgs(args, p)
  File "/opt/anaconda3/envs/RAiDER/lib/python3.7/site-packages/RAiDER-0.0.1-py3.7-macosx-10.9-x86_64.egg/RAiDER/checkArgs.py", line 42, in checkArgs
    lat, lon, llproj, bounds, flag, pnts_file = readLL(args.query_area)
  File "/opt/anaconda3/envs/RAiDER/lib/python3.7/site-packages/RAiDER-0.0.1-py3.7-macosx-10.9-x86_64.egg/RAiDER/llreader.py", line 33, in readLL
    fname = ' '.join(*args)
TypeError: sequence item 0: expected str instance, float found
```

**Comment by jlmaurer** [comment] 2021-03-08 20:11
@leiyangleon This is actually not the same bug, but I can't reproduce the error either way because I'm getting a KeyError in the _load_model_level function in gmao.py. Can you tell me if there is a quick fix for this? 

<details>
(RAiDER) jlmd9g@rt01jlmd9g tmp1 % raiderDelay.py --date 20200103 --time 23:00:00 -b 39 40 -79 -78 --model GMAO --zref 15000 --heightlvs 0 100 200 -v
Weather model GMAO is available from 2014-02-20 00:00:00-Present
WARNING: Rounded given hour from  23 to 0
ERROR: Unable to save weathermodel to file
Traceback (most recent call last):
  File "/Users/jlmd9g/software/miniconda3/envs/RAiDER/lib/python3.8/site-packages/RAiDER-0.0.1-py3.8-macosx-10.9-x86_64.egg/RAiDER/models/gmao.py", line 143, in _fetch
    writeWeatherVars2NETCDF4(self, lats, lons, h, q, p, t, outName=out)
  File "/Users/jlmd9g/software/miniconda3/envs/RAiDER/lib/python3.8/site-packages/RAiDER-0.0.1-py3.8-macosx-10.9-x86_64.egg/RAiDER/utilFcns.py", line 730, in writeWeatherVars2NETCDF4
    nc_outfile = write2NETCDF4core(nc_outfile, dimension_dict, dataset_dict, tran, mapping_name='WGS84')
  File "/Users/jlmd9g/software/miniconda3/envs/RAiDER/lib/python3.8/site-packages/RAiDER-0.0.1-py3.8-macosx-10.9-x86_64.egg/RAiDER/utilFcns.py", line 801, in write2NETCDF4core
    dataset_dict[data]['dataset'][np.isnan(dataset_dict[data]['dataset'])] = FillValue
TypeError: only integer scalar arrays can be converted to a scalar index
Traceback (most recent call last):
  File "/Users/jlmd9g/software/miniconda3/envs/RAiDER/bin/raiderDelay.py", line 4, in <module>
    __import__('pkg_resources').run_script('RAiDER==0.0.1', 'raiderDelay.py')
  File "/Users/jlmd9g/software/miniconda3/envs/RAiDER/lib/python3.8/site-packages/pkg_resources/__init__.py", line 650, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/Users/jlmd9g/software/miniconda3/envs/RAiDER/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1446, in run_script
    exec(code, namespace, namespace)
  File "/Users/jlmd9g/software/miniconda3/envs/RAiDER/lib/python3.8/site-packages/RAiDER-0.0.1-py3.8-macosx-10.9-x86_64.egg/EGG-INFO/scripts/raiderDelay.py", line 12, in <module>
    parseCMD()
  File "/Users/jlmd9g/software/miniconda3/envs/RAiDER/lib/python3.8/site-packages/RAiDER-0.0.1-py3.8-macosx-10.9-x86_64.egg/RAiDER/runProgram.py", line 196, in parseCMD
    _tropo_delay(new_args)
  File "/Users/jlmd9g/software/miniconda3/envs/RAiDER/lib/python3.8/site-packages/RAiDER-0.0.1-py3.8-macosx-10.9-x86_64.egg/RAiDER/runProgram.py", line 208, in _tropo_delay
    (_, _) = tropo_delay(args_copy)
  File "/Users/jlmd9g/software/miniconda3/envs/RAiDER/lib/python3.8/site-packages/RAiDER-0.0.1-py3.8-macosx-10.9-x86_64.egg/RAiDER/delay.py", line 113, in tropo_delay
    weather_model_file = prepareWeatherModel(
  File "/Users/jlmd9g/software/miniconda3/envs/RAiDER/lib/python3.8/site-packages/RAiDER-0.0.1-py3.8-macosx-10.9-x86_64.egg/RAiDER/processWM.py", line 91, in prepareWeatherModel
    f = weather_model.load(
  File "/Users/jlmd9g/software/miniconda3/envs/RAiDER/lib/python3.8/site-packages/RAiDER-0.0.1-py3.8-macosx-10.9-x86_64.egg/RAiDER/models/weatherModel.py", line 201, in load
    self.load_weather(*args, **kwargs)
  File "/Users/jlmd9g/software/miniconda3/envs/RAiDER/lib/python3.8/site-packages/RAiDER-0.0.1-py3.8-macosx-10.9-x86_64.egg/RAiDER/models/gmao.py", line 156, in load_weather
    self._load_model_level(f)
  File "/Users/jlmd9g/software/miniconda3/envs/RAiDER/lib/python3.8/site-packages/RAiDER-0.0.1-py3.8-macosx-10.9-x86_64.egg/RAiDER/models/gmao.py", line 168, in _load_model_level
    h = np.array(f.variables['H'][:])
KeyError: 'H'
</details>

**Comment by leiyangleon** [comment] 2021-03-08 20:14
@jlmaurer not sure what the cause is as I have never seen that error before. Would suggest to try other models. I suspect this is not related to GMAO only as I haven't touched the GMAO code for months...

**Comment by jlmaurer** [comment] 2021-03-10 01:40
@leiyangleon that is odd. Before I was getting this error if I changed my query points without deleting the query points file, which is the issue that should be fixed now. I will investigate further.

**Comment by jlmaurer** [comment] 2021-03-10 14:20
@leiyangleon I found the issue; I was not using the --heightlvs argument before, which is the source of the bug. The issue occurs [here](https://github.com/dbekaert/RAiDER/blob/c0dd130aa89aef7b6494b551bedc2f1d9b1a0218/tools/RAiDER/dem.py#L54). I will push a fix hopefully later today.

**Closed** 2021-08-07 04:20 UTC
Labels: bug
