### ISSUE TITLE
lighter raider-base with fewer dependencies

### ISSUE THREAD

**Issue by hfattahi** [dbekaert/RAiDER#533] opened 2023-05-06 14:28 UTC
We are trying to use Raider for tropospheric delay estimation within NISAR workflows. The current release of [ISCE3 v0.12.0](https://github.com/isce-framework/isce3/releases) includes at least one workflow in the NISAR package which relies on Raider.

However, we are currently blocked from adding Raider-Base to the runtime dependencies of the next conda-forge release of ISCE3. This is because Conda is unable to resolve dependencies when raider-base is included. The environment is not easily resolvable due to the large number of [raider dependencies](https://github.com/conda-forge/raider-feedstock/blob/14b8e6036e83ce679faacec1a6a99ae18f33a04c/recipe/meta.yaml#L37-L62), many of which do not seem to be used by the functionality we need for NISAR, such as matplotlib, pandas, boto3, cfgrib, s3fs, ecmwf-api-client, pydap, and probably more. All we need is the tropo_delay function and any parts of Raider it calls internally.

We believe an ideal solution would be to decouple the core computation functionalities from many analysis and visualization tools to get to a much lighter Raider-Base. In that case, we think there should be other projects/repositories that could call the Raider-Base to build their workflows, analysis, and visualization tools.

We understand this is not an easy issue to tackle or resolve. We just wanted to document this issue and inquire if the Raider team has a plan to decouple the core functionalities from other parts that may not be needed by many users.

**Comment by jhkennedy** [comment] 2023-05-17 00:28
@hfattahi Generally, we *do* want those dependencies and the functionality they support, but I can understand wanting a lighter RAiDER library with just some of the core functionality. 

`raider-base` was created specifically to drop the `isce3` requirement from RAiDER as requested by the NISAR ADT as discussed in https://github.com/dbekaert/RAiDER/discussions/463, so this:

> However, we are currently blocked from adding Raider-Base to the runtime dependencies of the next conda-forge release of ISCE3

doesn't surprise me as we haven't solved the fundamental issue. RAiDER wants ISCE3 core functionality (i.e., an ISCE3-base) and ISCE3 wants some core RAiDER functionality. That is both "packages" have been developed as *applications*, but there's a need for some common, core *libraries*. Notably, ISCE3 does bill itself as a library in its readme:

> The InSAR Scientific Computing Environment (ISCE) is an open-source library for processing spaceborne and airborne Interferometric Synthetic Aperture Radar (InSAR) data.
>
> This project is a successor to the [ISCE2](https://github.com/isce-framework/isce2) framework. It is a ground-up redesign focusing on improved modularity, documentation, and test-driven development.

And this whole issue may be resolved by separating out the ISCE3 library from he NISAR ADT application.


As before, this is a feature request for *new* development of RAiDER to specifically support the NISAR ADT, not a bug in RAiDER or `raider-base`, so I've relabeled this appropriately. 

This sounds like a significant undertaking and will require heavy code refactoring, so both the RAiDER and NISAR teams will need to coordinate the work up-front since I don't think any of the RAiDER developers are on the NISAR development team.

However, I'm unsure if/when any of the RAiDER developers will have time or interest in working on this -- I personally won't have the capacity to undertake something like that until *at least* fall, and likely not even then unless I was funded directly to do so.  

That said, this is an open-source and openly-developed package. The NISAR team is more than welcome to open PRs restructuring RAiDER into a base package and include the rest of the functionality as optional extras; I'd be happy to review any PRs in that case.

**Comment by jlmaurer** [comment] 2023-05-19 15:47
@hfattahi also just to add a bit to what @jhkennedy pointed out, the core RAiDER functionality uses quite a few of those packages besides matplotlib. I'm in a similar position as @jhkennedy but I will take a look in the next few weeks to see if there are any easy wins where we could remove some packages not needed in raider-base

**Comment by dbekaert** [comment] 2023-05-26 17:25
@hfattahi Can you confirm:
1) Are you using API for ECWMF if not, how do you load data in RAiDER?
2) What workflow will NISAR use in RaiDER. Please provide the exact call so we can see the path of dependancies.

**Comment by hfattahi** [comment] 2023-05-26 17:53
@dbekaert [here](https://github.com/isce-framework/isce3/blob/develop/python/packages/nisar/workflows/troposphere.py#L16) is how we use RAiDER.

**Comment by dbekaert** [comment] 2023-05-26 19:22
Perfect thanks @hfattahi. I noted the mapping of "hydro" and "dry" in the code at few locations. They are not the same and historically have been not used correctly. Please verify if you are referring to dry or hydro delay. If truly "dry" then total pressure is not used, rather dry portion of the pressure.

**Comment by dbekaert** [comment] 2023-05-26 19:23
@jlmaurer see above for code use of Raider in ISCE3

**Comment by dbekaert** [comment] 2023-09-27 16:51
@jlmaurer can you reference here the notebooks as there were some small udpates. Also update status to issue ticket and close if we don't intent to move further imports.

**Comment by jlmaurer** [comment] 2023-09-28 18:58
We have moved imports around quite a bit now and updated the documentation to match (#549). This allows for importing RAiDER without importing isce3, and keeps as many dependencies imported "at the last minute" as possible. Remaining imports are needed for core funcionality.

**Closed by jlmaurer** 2023-09-28 18:58 UTC
Labels: enhancement, help wanted, NISAR
